import './globals.css'
import { Inter } from 'next/font/google'

import { Header } from '@/components/header'
import { NextAuthProvider } from '@/components/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'WoW Raid Planner',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className + ' h-screen flex flex-col bg-neutral-800 text-white'}>
        <NextAuthProvider>
          <header className="shrink-0">
            {/* @ts-expect-error Server Component */}
            <Header />
          </header>
          <main className="flex-1 overflow-y-auto">{children}</main>
        </NextAuthProvider>
      </body>
    </html>
  )
}
